function [A,M] = PoissonCG2D()

% function [A,M] = PoissonCG2D()
% Purpose: Set up matrix for 2D Poisson equation based on stabilized 
%          internal fluxes on symmetric form

Globals3D;
GlobalsCG3D;

A = sparse(nTotal, nTotal);  M = sparse(nTotal, nTotal); 

% Build matrices -- local matrices in DG formulation are written into the
% corresponding place in CG enumeration
for k=1:K
  Sx = (diag(rx(:,k))*Dr)'*MassMatrix*(diag(rx(:,k))*Dr)...
     + (diag(rx(:,k))*Dr)'*MassMatrix*(diag(sx(:,k))*Ds)...
     + (diag(sx(:,k))*Ds)'*MassMatrix*(diag(rx(:,k))*Dr)...
     + (diag(rx(:,k))*Dr)'*MassMatrix*(diag(tx(:,k))*Dt)...
     + (diag(tx(:,k))*Dt)'*MassMatrix*(diag(rx(:,k))*Dr)...
     + (diag(tx(:,k))*Dt)'*MassMatrix*(diag(sx(:,k))*Ds)...
     + (diag(sx(:,k))*Ds)'*MassMatrix*(diag(tx(:,k))*Dt)...
     + (diag(tx(:,k))*Dt)'*MassMatrix*(diag(tx(:,k))*Dt)...
     + (diag(sx(:,k))*Ds)'*MassMatrix*(diag(sx(:,k))*Ds);
  Sy = (diag(ry(:,k))*Dr)'*MassMatrix*(diag(ry(:,k))*Dr)...
     + (diag(ry(:,k))*Dr)'*MassMatrix*(diag(sy(:,k))*Ds)...
     + (diag(sy(:,k))*Ds)'*MassMatrix*(diag(ry(:,k))*Dr)...
     + (diag(ry(:,k))*Dr)'*MassMatrix*(diag(ty(:,k))*Dt)...
     + (diag(ty(:,k))*Dt)'*MassMatrix*(diag(ry(:,k))*Dr)...
     + (diag(ty(:,k))*Dt)'*MassMatrix*(diag(sy(:,k))*Ds)...
     + (diag(sy(:,k))*Ds)'*MassMatrix*(diag(ty(:,k))*Dt)...
     + (diag(ty(:,k))*Dt)'*MassMatrix*(diag(ty(:,k))*Dt)...
     + (diag(sy(:,k))*Ds)'*MassMatrix*(diag(sy(:,k))*Ds);
  Sx = (diag(rz(:,k))*Dr)'*MassMatrix*(diag(rz(:,k))*Dr)...
     + (diag(rz(:,k))*Dr)'*MassMatrix*(diag(sz(:,k))*Ds)...
     + (diag(sz(:,k))*Ds)'*MassMatrix*(diag(rz(:,k))*Dr)...
     + (diag(rz(:,k))*Dr)'*MassMatrix*(diag(tz(:,k))*Dt)...
     + (diag(tz(:,k))*Dt)'*MassMatrix*(diag(rz(:,k))*Dr)...
     + (diag(tz(:,k))*Dt)'*MassMatrix*(diag(sz(:,k))*Ds)...
     + (diag(sz(:,k))*Ds)'*MassMatrix*(diag(tz(:,k))*Dt)...
     + (diag(tz(:,k))*Dt)'*MassMatrix*(diag(tz(:,k))*Dt)...
     + (diag(sz(:,k))*Ds)'*MassMatrix*(diag(sz(:,k))*Ds);
  
  %J(1,k)*(Sx+Sy)
  M(gmap(k,:), gmap(k,:)) = M(gmap(k,:), gmap(k,:)) + J(1,k)*MassMatrix;
  A(gmap(k,:), gmap(k,:)) = A(gmap(k,:), gmap(k,:)) + J(1,k)*(Sx+Sy+Sz);
end
return